DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS items cascade;
DROP TABLE IF EXISTS requests cascade;
DROP TABLE IF EXISTS bookings cascade;
DROP TABLE IF EXISTS comments cascade;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  requester_id INTEGER NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE,
  FOREIGN KEY (requester_id) REFERENCES users(id),
  CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  available BOOLEAN,
  owner_id INTEGER NOT NULL,
  request_id INTEGER,
  CONSTRAINT pk_item PRIMARY KEY (id),
  FOREIGN KEY (owner_id) REFERENCES users(id),
  FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE INDEX ix_owner_id ON items (owner_id);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  item_id INTEGER NOT NULL,
  booker_id INTEGER NOT NULL,
  status VARCHAR(255) NOT NULL,
  FOREIGN KEY (booker_id) REFERENCES users(id),
  FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE INDEX ix_item_id_bookings ON bookings (item_id);
CREATE INDEX ix_booker_id ON bookings (booker_id);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(512) NOT NULL,
  item_id INTEGER NOT NULL,
  author_id INTEGER NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE,
  FOREIGN KEY (author_id) REFERENCES users(id),
  FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE INDEX ix_item_id_comments ON comments (item_id);
CREATE INDEX ix_author_id ON comments (author_id);